let nomeHeroi = "Capitão America"
let experienciaHeroi = 800

if (experienciaHeroi <1000){
console.log("O heroi " + "O heroi " + nomeHeroi + " esta no nivel Ferro")

}else if (experienciaHeroi >= 1001 && experienciaHeroi <= 2000){
console.log("O heroi " + nomeHeroi + " esta no nivel Bronze")

}else if (experienciaHeroi >= 2001 && experienciaHeroi <= 5000){
    console.log("O heroi " + nomeHeroi + " esta no nivel Prata Ouro")

}else if (experienciaHeroi >= 5001 && experienciaHeroi <= 8000){
    console.log("O heroi " + nomeHeroi + " esta no nivel Platina Diamente")

}else if (experienciaHeroi >= 8001 && experienciaHeroi <= 9000){
    console.log("O heroi " + nomeHeroi + " esta no nivel Ascendente")

}else if (experienciaHeroi >= 9001 && experienciaHeroi <= 10000){
    console.log("O heroi " + nomeHeroi + " esta no nivel Imortal")

}else {console.log("O heroi " + nomeHeroi + " esta no nivel Radiante")}